# Generated by Django 3.2.10 on 2023-05-27 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_data',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 27, 20, 0, 35, 441535, tzinfo=utc)),
        ),
    ]
