# Generated by Django 3.2.10 on 2023-05-27 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_created_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_data',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
